// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/Footer.vue')['default']
    HomeNavigation: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/HomeNavigation.vue')['default']
    ImagesBackground: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/ImagesBackground.vue')['default']
    'ImagesBackground copy': typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/ImagesBackground copy.vue')['default']
    ImagesRow: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/ImagesRow.vue')['default']
    'ImagesRow copy': typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/ImagesRow copy.vue')['default']
    Navigation: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/Navigation.vue')['default']
    OldImagesBackground: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/old/OldImagesBackground.vue')['default']
    OldImagesRow: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/old/OldImagesRow.vue')['default']
    OldSingleImage: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/old/OldSingleImage.vue')['default']
    README: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/README.md')['default']
    SingeImage: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/SingeImage.vue')['default']
    SingleImage: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/SingleImage.vue')['default']
    StartAnimation: typeof import('C:/Users/robbe/Work/FunStuff/anna/src/components/home/StartAnimation/StartAnimation.vue')['default']
  }
}

export { }
